spring.application.name=restaurant-service
# -------------------------------
# Server configuration
# -------------------------------
server.port=8082

# -------------------------------
# Database (PostgreSQL)

# -------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/fooddelivery
spring.datasource.username=postgres
spring.datasource.password=syrine1254xxy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -------------------------------
# Eureka client
# -------------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# -------------------------------
# Optional: Logging & Actuator
# -------------------------------
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

management.endpoints.web.exposure.include=*
spring.cloud.config.enabled=false

