name: Food Delivery Microservices CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: syrinehusseyni

jobs:

  # ============================================
  # BACKEND MICROSERVICES (MATRIX - CLEAN WAY)
  # ============================================
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: user-service
            path: backend/user-service
          - name: order-service
            path: backend/order-service
          - name: restaurant-service
            path: backend/restaurant-service
          - name: admin-service
            path: backend/admin-service
          - name: delivery-service
            path: backend/delivery-service
          - name: api-gateway
            path: backend/api-gateway
          - name: eureka-server
            path: backend/eureka-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
          cache: maven

      - name: Build JAR
        working-directory: ${{ matrix.service.path }}
        run: mvn clean package -DskipTests

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker Image
        run: docker build -t $REGISTRY/$IMAGE_OWNER/${{ matrix.service.name }}:latest ${{ matrix.service.path }}

      - name: Push Docker Image
        if: github.event_name == 'push'
        run: docker push $REGISTRY/$IMAGE_OWNER/${{ matrix.service.name }}:latest


  # ============================================
  # FRONTEND (React / Angular / Vue etc.)
  # ============================================
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build